[workshop]
# this is a name that will be added to the EC2 instances and will become a
# prefix for the notebook URLs
group_name =
[ec2]
# amazon ec2 image identifier
ami =
# name of the keypair pem file used to ssh into EC2 machines
# this should match the one set on the EC2 AWS instances
keypair_name =
# path to the key pair (usually ~/.ssh)
keypair_path =
# name of the security group the instances should use
# this should be setup in AWS in advance and allow
# both http and https traffic in and out of the instance
security_group =
# type of EC2 cloud machine for the instances
instance_type =
# proxy IP address that will be used for the
# proxy server that redirects the human readable
# notebook URLs to the EC2 machines
proxy_ip =
[repo]
# location of the workshop content repo where the jupyter server should be
# started on the instances
repo_location =
# branch of the repo to checkout and use (if any)
branch_name =